version: '3'
services:
  caddy:
    image: "caddy:2-alpine"
    restart: unless-stopped
    ports:
        - "443:443"
        - "443:443/udp"
    volumes:
        - $PWD/Caddyfile:/etc/caddy/caddyfile
        - $PWD/site:/srv
        - $PWD/caddy_data:/data
        - $PWD/caddy_config:/config
  
