version: '3'
services:
  caddy:
    image: "docker.io/caddy:2-alpine"
    restart: unless-stopped
    ports:
        - "443:443"
        - "443:443/udp"
    volumes:
        - $PWD/caddy/Caddyfile:/etc/caddy/Caddyfile
        - $PWD/caddy/site:/srv
        - $PWD/caddy/caddy_data:/data
        - $PWD/caddy/caddy_config:/config
  v2ray:
    image: "docker.io/v2fly/v2fly-core"
    restart: unless-stopped
    volumes:
      - $PWD/v2ray/config.json:/etc/v2ray/config.json:ro
  
